bv_static_cms_page_upload:
    path:     /cmspageupload
    defaults: { _controller: FrontBundle:Default:CmsPageUpload }
bv_static_volley_school:
    path:     /volleyschool
    defaults: { _controller: FrontBundle:Default:volleySchool }
bv_static_volley_school_edit:
    path:     /volleyschool/edit
    defaults: { _controller: FrontBundle:Default:volleySchoolEdit }
bv_static_jeu_libre:
    path:     /jeulibre
    defaults: { _controller: FrontBundle:Default:jeuLibre }
bv_static_jeu_libre_edit:
    path:     /jeulibre/edit
    defaults: { _controller: FrontBundle:Default:jeuLibreEdit }
bv_static_addresses:
    path:     /addresses
    defaults: { _controller: FrontBundle:Default:addresses }
bv_static_addresses_edit:
    path:     /addresses/edit
    defaults: { _controller: FrontBundle:Default:addressesEdit }
bv_static_schedule:
    path:     /schedule
    defaults: { _controller: FrontBundle:Default:schedule }
bv_static_schedule_edit:
    path:     /schedule/edit
    defaults: { _controller: FrontBundle:Default:scheduleEdit }