## FOS USER SECURITY
fos_user_security_login:
    defaults: { _controller: "FOSUserBundle:Security:login" }
    path:     /login
fos_user_security_check:
    defaults: { _controller: "FOSUserBundle:Security:check" }
    path:     /login_check
    requirements:
        _method:  POST
fos_user_security_logout:
    defaults: { _controller: "FOSUserBundle:Security:logout" }
    path:     /logout

## FOS USER REGISTRATION
fos_user_registration_register: ## OVERRIDE Registration
    defaults: { _controller: "FrontBundle:Registration:register" }
    path:     /register/
fos_user_registration_check_email:
    defaults: { _controller: "FOSUserBundle:Registration:checkEmail" }
    path:     /register/check-email
    requirements:
        _method:  GET
fos_user_registration_confirm:
    defaults: { _controller: "FOSUserBundle:Registration:confirm" }
    path:     /register/confirm/{token}
    requirements:
        _method:  GET
fos_user_registration_confirmed:
    defaults: { _controller: "FOSUserBundle:Registration:confirmed" }
    path:     /register/confirmed
    requirements:
        _method:  GET

## FOS USER RESETTING
fos_user_resetting_request:
    defaults: { _controller: "FOSUserBundle:Resetting:request" }
    path:     /resetting/request
    requirements:
        _method:  GET
fos_user_resetting_send_email:
    defaults: { _controller: "FOSUserBundle:Resetting:sendEmail" }
    path:     /resetting/send-email
    requirements:
        _method:  POST
fos_user_resetting_check_email:
    defaults: { _controller: "FOSUserBundle:Resetting:checkEmail" }
    path:     /resetting/check-email
    requirements:
        _method:  GET
fos_user_resetting_reset:
    defaults: { _controller: "FOSUserBundle:Resetting:reset" }
    path:     /resetting/reset/{token}
    requirements:
        _method:  GET|POST

## FOS USER CHANGE PASSWORD
fos_user_change_password:
    defaults: { _controller: "FOSUserBundle:ChangePassword:changePassword" }
    path:     /profile/change-password
    requirements:
        _method:  GET|POST

## FOS USER PROFILE
fos_user_profile_show:
    defaults: { _controller: "FOSUserBundle:Profile:show" }
    path:     /profile
fos_user_profile_edit:  ## OVERRIDE Profile Edition
    defaults: { _controller: "FrontBundle:Profile:edit" }
    path:     /profile/edit
bv_user_update_informations_request:  ## ADD Profile Send change request
    defaults: { _controller: "FrontBundle:Profile:updateRequest" }
    path:     /profile/updateRequest
