#!/bin/bash

# load custom env
for VAR in `ls ~/.env/user_vars`; do
    declare "$VAR=`cat ~/.env/user_vars/$VAR`"
    export $VAR
done

### DIRECTORIES ###
LINKED_DIRS="vendor node_modules bower_components"

for DIR in $LINKED_DIRS; do
    # check data dir
    if [ ! -d "$OPENSHIFT_DATA_DIR/$DIR" ]; then
        mkdir $OPENSHIFT_DATA_DIR/$DIR
        chmod -R 0777 $OPENSHIFT_DATA_DIR/$DIR
    fi
    # check symlink
    if [ ! -d "$OPENSHIFT_REPO_DIR/$DIR" ]; then
        ln -s $OPENSHIFT_DATA_DIR/$DIR $OPENSHIFT_REPO_DIR/$DIR
    fi
done

(
    cd $OPENSHIFT_REPO_DIR

    ### NODE ###
    # Dependencies
    npm install
    # Front libraries
    HOME=$OPENSHIFT_DATA_DIR bower install
    # Compile Less files
    grunt less

    ### COMPOSER ###
    unset GIT_DIR
    php $OPENSHIFT_DATA_DIR/composer.phar install --no-dev --no-progress --optimize-autoloader

    ### SYMFONY ###
    # Database
    php app/console doctrine:migrations:migrate --no-interaction
    # Cache
    php app/console cache:clear --env=prod --no-debug
    # Assetic assets
    php app/console assetic:dump --env=prod --no-debug
)
