#!/bin/bash

### ENVIRONMENT ###
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"
export NPM_CONFIG_USERCONFIG="$OPENSHIFT_DATA_DIR/.npmrc"

# DB config (used by Composer Incenteev/ParameterHandler buildParameters hook)
export BV_DB_NAME=$OPENSHIFT_APP_NAME
export BV_DB_HOST=$OPENSHIFT_MYSQL_DB_HOST
export BV_DB_USERNAME=$OPENSHIFT_MYSQL_DB_USERNAME
export BV_DB_PASSWORD=$OPENSHIFT_MYSQL_DB_PASSWORD
export BV_SECRET=$OPENSHIFT_SECRET_TOKEN

### DIRECTORIES ###
LINKED_DIRS="vendor node_modules bower_components"

for DIR in $LINKED_DIRS; do
    # check data dir
    if [ ! -d "$OPENSHIFT_DATA_DIR/$DIR" ]; then
        mkdir $OPENSHIFT_DATA_DIR/$DIR
        chmod -R 0777 $OPENSHIFT_DATA_DIR/$DIR
    fi
    # check symlink
    if [ ! -d "$OPENSHIFT_REPO_DIR/$DIR" ]; then
        ln -s $OPENSHIFT_DATA_DIR/$DIR $OPENSHIFT_REPO_DIR/$DIR
    fi
done

### NPM ###
if [ ! -e $NPM_CONFIG_USERCONFIG ]; then
    npm set production true
fi

npm install

### BOWER ###
bower install

### COMPILE LESS ###
grunt less

### COMPOSER ###
(
    unset GIT_DIR
    cd $OPENSHIFT_REPO_DIR
    php $OPENSHIFT_DATA_DIR/composer.phar install --no-dev --no-progress --optimize-autoloader
)


### SYMFONY ###
(
    cd $OPENSHIFT_REPO_DIR
    # Database
    php app/console doctrine:migrations:migrate --no-interaction
    # Cache
    php app/console cache:clear --env=prod --no-debug
    # Assetic assets
    php app/console assetic:dump --env=prod --no-debug
)
