#!/bin/bash

### COMPOSER ###

# set the location for composer home to the data dir
export COMPOSER_HOME="$OPENSHIFT_DATA_DIR/.composer"

# check if composer exists in data dir
if [ ! -f "$OPENSHIFT_DATA_DIR/composer.phar" ]; then
    curl -s https://getcomposer.org/installer | php -- --install-dir=$OPENSHIFT_DATA_DIR
else
    php $OPENSHIFT_DATA_DIR/composer.phar self-update
fi

# check vendor dir
if [ ! -d "$OPENSHIFT_DATA_DIR/vendor" ]; then
    mkdir $OPENSHIFT_DATA_DIR/vendor
    chmod -R 0777 $OPENSHIFT_DATA_DIR/vendor
fi

# check symlink for vendor dir
if [ ! -d "$OPENSHIFT_REPO_DIR/vendor" ]; then
    ln -s $OPENSHIFT_DATA_DIR/vendor $OPENSHIFT_REPO_DIR/vendor
fi

# use composer install
(
    unset GIT_DIR

    export BV_DB_HOST=$OPENSHIFT_MYSQL_DB_HOST
    export BV_DB_USERNAME=$OPENSHIFT_MYSQL_DB_USERNAME
    export BV_DB_PASSWORD=$OPENSHIFT_MYSQL_DB_PASSWORD
    export BV_SECRET=$OPENSHIFT_GEAR_UUID

    cd $OPENSHIFT_REPO_DIR
    php $OPENSHIFT_DATA_DIR/composer.phar install --no-dev --no-progress --optimize-autoloader
)

### SYMFONY ###
(
    cd $OPENSHIFT_REPO_DIR
    # Database
    php app/console doctrine:migrations:migrate --no-interaction
    # Cache
    php app/console cache:clear --env=prod --no-debug
    # Assetic assets
    php app/console assetic:dump --env=prod --no-debug
)
