<?php

namespace BV\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * EventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventsRepository extends EntityRepository
{
    public function findSingleBySchedulerId($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('SELECT p FROM FrontBundle:Events p WHERE p.schedulerId = :id')
            ->setParameter('id', $id);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }
}
