imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    translator: ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

braincrafted_bootstrap:
    output_dir:
    assets_dir:      %kernel.root_dir%/../bower_components/bootstrap
    fontawesome_dir: %kernel.root_dir%/../bower_components/font-awesome
    jquery_path:     %kernel.root_dir%/../bower_components/jquery/dist/jquery.min.js
    fonts_dir:       %kernel.root_dir%/../web/fonts
    less_filter:     lessphp # "less", "lessphp", "sass" or "none"
    icon_prefix:     fa
    auto_configure:
        assetic:       false
        twig:          true
        knp_menu:      true
        knp_paginator: true

# FOS User Bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: BV\FrontBundle\Entity\User

# Genemu Form Bundle
genemu_form:
    recaptcha:
        public_key:  '6LeTHfwSAAAAAET_S2v5iO5QkYZrSqJbP1ZPHnTJ'
        private_key: '6LeTHfwSAAAAAHl-UnCNJw-OJVv2wYy-37XXxI8N'
        enabled:              true
        validation:
            host:                 www.google.com
            port:                 80
            path:                 /recaptcha/api/verify
            timeout:              10
            code:                 ~
        configs:              []
