home:
    path:     /
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:index }

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

application_sonata_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"

static:
    path:     /{page}
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:static }
