user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

team:
    resource: "@TeamBundle/Resources/config/routing.yml"
    prefix:   /

FOS_User:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

home:
    path:     /
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:index }

news:
    resource: "@BlagnacVolleyWebsiteBundle/Resources/config/routing.yml"

contact:
    path:     /contact
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:contact }
contactPost:
    path:     /contactPost
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:contactPost }

static:
    path:     /{page}
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:static }
