admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

########################
####  STATIC PAGES  ####
########################

home:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: FrontBundle:Contact:contact }

contactPost:
    path:     /contactPost
    defaults: { _controller: FrontBundle:Contact:contactPost }

_imagine:
    resource: .
    type:     imagine

_console:
    resource: "@CoreSphereConsoleBundle/Resources/config/routing.yml"
    prefix: /_console