home:
    path:     /
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:index }

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

news:
    resource: '@SonataNewsBundle/Resources/config/routing/news.xml'
    prefix: /news

application_sonata_user:
    resource: "@ApplicationSonataUserBundle/Resources/config/routing.yml"

contact:
    path:     /contact
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:contact }

#craue_config_settings:
#    resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
#    prefix: /settings
#
#LexikMailerBundle:
#    resource: "@LexikMailerBundle/Resources/config/routing.xml"
#    prefix:   /emails

static:
    path:     /{page}
    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:static }