admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

#user:
#    resource: "@UserBundle/Controller/"
#    type:     annotation
#    prefix:   /

########################
####  STATIC PAGES  ####
########################

home:
    path:     /
    defaults: { _controller: FrontBundle:Default:index }

contact:
    path:     /contact
    defaults: { _controller: FrontBundle:Contact:contact }

contactPost:
    path:     /contactPost
    defaults: { _controller: FrontBundle:Contact:contactPost }

#static:
#    path:     /{page}
#    defaults: { _controller: BlagnacVolleyWebsiteBundle:Default:static }
