sonata_core:
    form_type: horizontal

sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    templates:
        layout: AdminBundle::layout.html.twig
        edit: SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        groups:
            sonata_user:
                label:  'Utilisateurs'
                icon:   '<i class="fa fa-users"></i>'
            Content:
                label:  'Contenu'
                icon:   '<i class="fa fa-folder"></i>'
            Calendrier:
                label:  'Calendrier'
                icon:   '<i class="fa fa-calendar"></i>'
            Paramètres:
                label:    'Paramètres'
                icon:    '<i class="fa fa-cogs"></i>'


sonata_user:
    manager_type: orm
    class:
        user:  BV\FrontBundle\Entity\User
        group: BV\FrontBundle\Entity\Group
    table:
        user_group: bv_user_group
    admin:
        user:
            class: BV\AdminBundle\Admin\UserAdmin
            translation: BVUserBundle

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)

sonata_notification:
    backend: sonata.notification.backend.runtime
    admin:
        enabled: false
