front_team:
    resource: "@FrontBundle/Resources/config/routing/team.yml"
    prefix:   /teams

front_fos_user:
    resource: "@FrontBundle/Resources/config/routing/user.yml"
    prefix:   /

front_news:
    resource: "@FrontBundle/Resources/config/routing/news.yml"

front_calendar:
    resource: "@FrontBundle/Resources/config/routing/calendar.yml"

front_static:
    resource: "@FrontBundle/Resources/config/routing/static.yml"

front_homepage:
    path:     /hello
    defaults: { _controller: FrontBundle:Default:index }
