front_team:
    resource: "@FrontBundle/Resources/config/routing/team.yml"
    prefix:   /teams

front_fos_user:
    resource: "@FrontBundle/Resources/config/routing/user.yml"
    prefix:   /

front_homepage:
    path:     /hello/{name}
    defaults: { _controller: FrontBundle:Default:index }

register:
    path:     /register
    defaults: { _controller: FrontBundle:User:register }
