admin_homepage:
    path:     /hello/{name}
    defaults: { _controller: AdminBundle:Default:index }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

bv_delete_file:
    path:     /deleteFile
    defaults: { _controller: AdminBundle:Default:deleteFile }