<?php

namespace BV\FrontBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function findSingleByName($name)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT p FROM FrontBundle:Email p WHERE p.name = :name")
            ->setParameter('name', $name);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }
}
